import { useState } from 'react';

export default function DocumentCreator() {
  const [directoryHandle, setDirectoryHandle] = useState(null);
  const [folderName, setFolderName] = useState('No folder selected');
  const [fileName, setFileName] = useState('');
  const [fileExtension, setFileExtension] = useState('.txt');
  const [statusMessage, setStatusMessage] = useState('');

  // 1. Ask the user for permission to a local folder
  const handleSelectFolder = async () => {
    try {
      // Opens the native OS folder picker
      const handle = await window.showDirectoryPicker();
      setDirectoryHandle(handle);
      setFolderName(handle.name);
      setStatusMessage('');
    } catch (error) {
      console.error(error);
      setStatusMessage('❌ Folder selection was cancelled or failed.');
    }
  };

  // 2. Generate the actual file in that folder
  const handleCreateDocument = async (e) => {
    e.preventDefault();
    if (!directoryHandle) {
      setStatusMessage('⚠️ Please select a local folder first.');
      return;
    }
    if (!fileName.trim()) {
      setStatusMessage('⚠️ Please type a file name.');
      return;
    }

    const fullFileName = `${fileName}${fileExtension}`;
    setStatusMessage(`Creating ${fullFileName}...`);

    try {
      // Tell the OS to create a new file in the authorized folder
      const fileHandle = await directoryHandle.getFileHandle(fullFileName, { create: true });
      
      // Open a stream to write data into the file
      const writableStream = await fileHandle.createWritable();
      
      // Determine what to write inside the file based on the extension
      let initialContent = '';
      if (fileExtension === '.txt' || fileExtension === '.md') {
        initialContent = `# ${fileName}\n\nDocument generated by Event-Sourced DMS.`;
      } 
      // Note: True .docx and .xlsx are complex binary zip files. 
      // For now, we create an empty shell file for them.
      
      await writableStream.write(initialContent);
      await writableStream.close();

      setStatusMessage(`✅ Successfully created ${fullFileName} in "${folderName}"!`);
      setFileName(''); // Clear the input

    } catch (error) {
      console.error(error);
      setStatusMessage(`❌ Error creating file: ${error.message}`);
    }
  };

  return (
    <div style={{ maxWidth: '500px', margin: '40px auto', padding: '20px', border: '1px solid #ccc', borderRadius: '8px', fontFamily: 'sans-serif' }}>
      <h2>Local Document Generator</h2>
      
      {/* Folder Selection Section */}
      <div style={{ marginBottom: '20px', padding: '15px', backgroundColor: '#f9f9f9', borderRadius: '6px' }}>
        <p><strong>Target Folder:</strong> {folderName}</p>
        <button onClick={handleSelectFolder} style={{ padding: '8px 12px', cursor: 'pointer' }}>
          📂 Select Local Folder
        </button>
      </div>

      {/* File Creation Form */}
      <form onSubmit={handleCreateDocument} style={{ display: 'flex', flexDirection: 'column', gap: '15px' }}>
        <label>
          <strong>Document Name:</strong><br/>
          <input 
            type="text" 
            value={fileName} 
            onChange={(e) => setFileName(e.target.value)} 
            placeholder="e.g., Q1_Financial_Report"
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          />
        </label>

        <label>
          <strong>Document Type:</strong><br/>
          <select 
            value={fileExtension} 
            onChange={(e) => setFileExtension(e.target.value)}
            style={{ width: '100%', padding: '8px', marginTop: '5px' }}
          >
            <option value=".txt">Plain Text (.txt)</option>
            <option value=".md">Markdown (.md)</option>
            <option value=".docx">MS Word (.docx)</option>
            <option value=".xlsx">MS Excel (.xlsx)</option>
            <option value=".csv">Data Sheet (.csv)</option>
          </select>
        </label>

        <button 
          type="submit" 
          disabled={!directoryHandle}
          style={{ 
            padding: '10px', 
            backgroundColor: directoryHandle ? '#28a745' : '#ccc', 
            color: 'white', border: 'none', cursor: directoryHandle ? 'pointer' : 'not-allowed',
            fontWeight: 'bold', borderRadius: '4px'
          }}
        >
          Create Document
        </button>
      </form>

      {statusMessage && (
        <div style={{ marginTop: '15px', fontWeight: 'bold', color: statusMessage.includes('❌') || statusMessage.includes('⚠️') ? 'red' : 'green' }}>
          {statusMessage}
        </div>
      )}
    </div>
  );
}